### ISSUE TITLE
line of sight changes should have STATE updates 

### ISSUE THREAD

**Issue by modgethanc** [vilmibm/tildemush#102]
such as: objects being dropped or picked up, player entering or leaving the room. i guess this can be generalized as objects entering or leaving the target's container (room or otherwise)?

this should also include a message to the game text, like "endorphant dropped a rock", "endorphant enters from above".

**Comment by modgethanc** [comment]
#73 also falls under this, i think!

**Comment by vilmibm** [comment]
fixed in https://github.com/vilmibm/tildemush/pull/176
