### ISSUE TITLE
scripts aren't being cleared from editing state after quitting editor

### ISSUE THREAD

**Issue by modgethanc** [vilmibm/tildemush#107]
the most recently edited script seems to remain marked as being edited even after closing/saving in the witch editor; switching to a new object clears this, but then the new object gets stuck. so, it's currently not possible to edit the same object twice in a row.

**Comment by modgethanc** [comment]
(a temporary workaround for this is to make some fake/buffer item and edit that to "clear" the editing state between scripts)

**Comment by vilmibm** [comment]
duplicates #136
