### ISSUE TITLE
Settings pane

### ISSUE THREAD

**Issue by vilmibm** [vilmibm/tildemush#108]

**Comment by modgethanc** [comment]
i started listing some client settings in #100, but it occurred to me that there's server-side settings, like account info, block list, etc. that should also go here. and also changing password (which i think there isn't even a utility for at the moment). some settings can be stored locally (like hotkeys, panel arrangement), especially if they're not strictly required/universal across possibly different clients, and thus having those attached to account info in the db probably doesn't make sense.

should the settings pane make a distinction between server settings and client settings, then? or is that likely to be confusing for a less technical user?

**Comment by vilmibm** [comment]
i think it's okay to have it all mixed together in the client presentation. if it gets confusing we can do something more explicit.

**Comment by vilmibm** [comment]
closing in favor of #100
