### ISSUE TITLE
colorized "say" output messed up reset in certain terminal color schemes

### ISSUE THREAD

**Issue by vilmibm** [vilmibm/tildemush#125]
i guess because the reset color is hardcoded?

![image](https://user-images.githubusercontent.com/98482/42926262-b4058dea-8ae5-11e8-9e22-0d0f2003fd85.png)

is it possible to clear color output? instead of returning to a predefined color?

also, should it be a bug that things uttered by non-players don't get the client side colorization?

**Comment by m455** [comment]
maybe the reset color should be the terminal default. this can be achieved by outputting the ansi escape code `\x1b[39m` ?

resetting background color is as follows: \x1b[49m

see SGR (Select Graphic Rendition) parameters in [https://en.wikipedia.org/wiki/ANSI_escape_code](https://en.wikipedia.org/wiki/ANSI_escape_code)

sorry if you already know this and i didn't understand the issue correctly haha

**Comment by m455** [comment]
clearing colour output is possible by outputting the ansi escape code `\x1b[39m`

and if you need it: resetting background color is as follows: `\x1b[49m`

see SGR (Select Graphic Rendition) parameters in [https://en.wikipedia.org/wiki/ANSI_escape_code](https://en.wikipedia.org/wiki/ANSI_escape_code)

so ideally, if you want to color the text, then reset right after, just like bash color configs, you can do:

(magenta + "chat text" + reset-color-code) 

in a very hard-coded manner as so:

`print("\x1b[35m" + "chat text" + "\x1b[39m")`

I think [here](https://github.com/vilmibm/tildemush/blob/fb522072eb6fda7818a2c33118704bd4b8b4f34f/client/tmclient/ui.py#L44) is where `('reset', 'white', '')]` should be changed to `('reset', 'default', '')]` according to [this](http://urwid.org/manual/displayattributes.html) i don't want to touch the code in fear of breaking it haha.

sorry if you already know this and i didn't understand the issue correctly haha. also, very sorry if you are getting emails every time i edited this comment been figuring it out at work on my cell phone haha.

**Comment by m455** [comment]
clearing colour output is possible by outputting the ansi escape code `\x1b[39m`

and if you need it: resetting background color is as follows: `\x1b[49m`

see SGR (Select Graphic Rendition) parameters in [https://en.wikipedia.org/wiki/ANSI_escape_code](https://en.wikipedia.org/wiki/ANSI_escape_code)

so ideally, if you want to color the text, then reset right after, just like bash color configs, you can do:

(magenta + "chat text" + reset-color-code) 

in a very hard-coded manner as so:

`print("\x1b[35m" + "chat text" + "\x1b[39m")`

I think [here](https://github.com/vilmibm/tildemush/blob/fb522072eb6fda7818a2c33118704bd4b8b4f34f/client/tmclient/ui.py#L44) is where `('reset', 'white', '')]` should be changed to `('reset', 'default', '')]` according to [this](http://urwid.org/manual/displayattributes.html) i don't want to touch the code in fear of breaking it haha.

sorry if you already know this and i didn't understand the issue correctly haha.

**Comment by modgethanc** [comment]
@m455 thanks for figuring this out!! i just pushed a patch for this by your suggestion :)
