### ISSUE TITLE
UI flesh out

### ISSUE THREAD

**Issue by vilmibm** [vilmibm/tildemush#13]
- [ ] settings
- [x] error messaging
- [x] WITCH editor modal
- [ ] map pane
- [x] user info pane
- [x] "look" pane

**Comment by modgethanc** [comment]
a thought on displaying some sense of activity even when the room is quiet; maybe the map or room information area just has a couple of ascii doodles that kind of gently 'sway'? i'm thinking like how the plants in the background of super mario world did that little dance, and would stop when you're paused, and it was a great visual cue.

relatedly, if there's a map, have more 'swaying'/'wiggling' in areas of the map with higher population/activity; something i really felt was missing in some of the MUDs i played in before was that even if i knew a lot of people were logged in, it was often hard to figure out where to go to find them (and obviously people should be able to make private rooms that don't signal this, maybe call them 'quiet' rooms or something).

**Comment by modgethanc** [comment]
thinking about a tab-based interface, like:

```
_____________________________________________________________________
| F1 MAIN | F2 WITCH | F3 WORLDMAP | F4 CHARACTER INFO | F5 SETTINGS |
|         |----------------------------------------------------------| 
|  (game chat)                          +----------------------------|
|                                       | look panel                 |
|                                       |____________________________|
|                                       | minimap                    |
|                                       |____________________________|
|                                       | character/quick status     |
|   >prompt                             |____________________________|
|____________________________________________________________________| 
```
character panel could include sticky output/monitoring on scripts/items (so scripts could have the option of outputting info to that panel?)

WITCH tab would be the full script editor, script inventory, etc.

character info for stuff like editing appearance, looking at stats/full status output

and settings mostly for client/meta things (including user blocking/muting)

**Comment by modgethanc** [comment]
also: thinking about the main screen panels being more user-configurable; like if there's a set collection of them, and as part of client settings, users can rearrange or add/remove them as they like? it might also be cool to have a plugin API eventually, so folks can write their own panels!

**Comment by vilmibm** [comment]
ahh, i somehow missed all of these comments D:

i love your thought about noting activity in a larger map. while i'm pretty sure right now we're not sure how to *build* that map, that's absolutely an idea i want to see realized.

another way to communicate distant activity is using idle moments to report on rumblings elsewhere:

```
(30-60 seconds of inactivity, but over in Ten Forward people are chatting)
You hear commotion in Ten Forward...
```

**Comment by modgethanc** [comment]
haha, no worries, i've just been dumping ideas here while too sleepy to do anything else.

i'm definitely head scratching on what to do with rendering a world map given how the room graph is being built at the moment.

i think that distant activity reporting could be a nice feature (when i was running txtminebot, whenever someone cleared a mine, the bot would report that in the main game channel as a 'distant rumbling', so you'd get a sense of activity based on how much rumbling you could hear). maybe this should be something you can toggle on and off, though, like if there's an equippable item that lets you listen for chatter? i can imagine the chat area getting cluttered with that kind of message.

**Comment by vilmibm** [comment]
this issue has some great ideas in it, but i think i'm going to mark it as closed since actual work to get done is captured elsewhere (eg #108 #155 )
