### ISSUE TITLE
WITCH editor should have a default value

### ISSUE THREAD

**Issue by modgethanc** [vilmibm/tildemush#133]
The PR for this needs to instead do:

`editor = os.environ.get('EDITOR', 'nano')`

---

currently, the editor checks `os.environ["EDITOR"]` for which text editor to launch, which crashes if the user doesn't have a default one set. the WITCH editor should have some default (maybe nano or pico or something simple) to launch in this case.

**Comment by archangelic** [comment]
Perhaps if the editor is launched, and there is no EDITOR set, give them some options for a default and store that in the user db?

**Comment by vilmibm** [comment]
for now let's decide on defaulting to either `nano` or `micro`. if a user is advanced enough to care, they can handle setting an environment variable IMO.

**Comment by vilmibm** [comment]
should be `os.environ.get('EDITOR')`
