### ISSUE TITLE
Dynamic "look" panel in UI

### ISSUE THREAD

**Issue by vilmibm** [vilmibm/tildemush#41]
To increase discoverability, there should be a panel in the UI that behaves like a perpetually run "look" command.

- [ ] the current room name
- [ ] the current room description
- [ ] the current list of objects in the room, updated as needed

**Comment by vilmibm** [comment]
Blocked by #37

**Comment by modgethanc** [comment]
ooh, i threw this together yesterday when i was learning my way around urwid! :)

![screenshot_2018-05-23_17-23-45](https://user-images.githubusercontent.com/5298005/40451908-23a6b192-5eae-11e8-8c6f-f3b5921814b5.png)

**Comment by modgethanc** [comment]
preview of the last commit, which is a super rough draft

![screenshot_2018-05-24_00-43-25](https://user-images.githubusercontent.com/5298005/40464832-8cfab6ba-5eeb-11e8-93e7-a65f184941be.png)

**Comment by vilmibm** [comment]
yoooo this is looking really cool!
