### ISSUE TITLE
handle user disconnect/reconnects

### ISSUE THREAD

**Issue by modgethanc** [vilmibm/tildemush#44]
i've just been hitting ctrl-c to kill the client, which leaves a copy of my user in the room; when i reconnect, it makes a duplicate entity. should users fade out of a room's visibility (or maybe appear as a ghost/shadow) on disconnect, and then hook up with that shadow once they reconnect?

i've been using 'reconstitute' as a filler word lately.

This should also cover clearing out any rows in the Editing table for the disconnecting user

**Comment by vilmibm** [comment]
i think i'm pretty into the shadow concept and am happy to start there.

this ticket can also include a /quit command that the client notices, so i'm adding the client label.

**Comment by modgethanc** [comment]
i just made a whole separate ticket for some details about quitting, since it was on my mind! but yeah, any client-side quit behavior should tie in to how the server handles disconnects.

**Comment by modgethanc** [comment]
this is probably a question for later in development, but should there be a distinction between proper quits vs. idle out, client crash, or otherwise abnormal disconnects? idle outs would mean implementing some sort of ping/pong system, at least.

**Comment by vilmibm** [comment]
hmmm, i think to start i'm cool with having every client disconnect result in a re-attachable ghost. we can see how people like that before adding more nuance.

for idle outs, the websocket library handles all of that already.

**Comment by vilmibm** [comment]
great idea.
