### ISSUE TITLE
Add panes to WITCH panel

### ISSUE THREAD

**Issue by vilmibm** [vilmibm/tildemush#77]
The WITCH panel in the client should have:

- a pane for either running $EDITOR or showing a read-only print-out of an object's code
- a pane with status: last synced with server timestamp, code revision number, any errors or suggestions from client side WITCH evaluation
- a pane with the GameObject being edited's current key/value data
- a pane with the GameObject being edited's permissions

This issue covers just stubbing these panes out; follow-up issues can be opened once stubs are in

**Comment by modgethanc** [comment]
here's a rough draft of how i think this could look!

![witchdraft](https://user-images.githubusercontent.com/5298005/42121957-a06f8a7a-7c07-11e8-8d80-3982a23da9ab.png)

**Comment by vilmibm** [comment]
I like it! I'm thinking like with client state, I'll push a payload of stuff the witch pane wants to display as needed.

I'm thinking something prefixed with OBJECT and a payload of keys like `shortname`, `data`, `permissions`, `code`, `current_rev`, `errors` and am going to add it to the PR i have going. They'll only show up for the last object that /edit was run on, is my current plan

**Comment by vilmibm** [comment]
> cool, that makes sense; i could have the client grab an OBJECT payload to propagate the witch pane and switch over automatically, and then on editor save have the new script sent back. validity check should probably be server-side?

I was thinking that the client would notice the /edit command and move to the pane then; otherwise, when an OBJECT update comes in (because, say, the object's key value data changed) we'd have to know not to rip them back to the edit pane from the main screen.

>  when there isn't a script loaded, maybe the panel just has a list of accessible scripts, and selecting one for editing basically just send a `/edit` command for that object?

I'm going back and forth on this. I kind of like the idea of making a player actually run /edit on a visible object; if they leave some machine clanking away in some room, they actually have to go there to fix it. is that just cruel, though?

**Comment by modgethanc** [comment]
haha actually i'm with you on that last bit, i think having to work on objects in person is a great idea. i guess it's not a big deal for the witch panel to just be empty when no object is being edited (maybe just have a list of objects in scope or something?)

**Comment by vilmibm** [comment]
empty is fine, at least to start, but the objects in scope is a great idea!! I think the client state payload can be used for that? esp. once it includes shortname...
