### ISSUE TITLE
decide what to do about /move

### ISSUE THREAD

**Issue by vilmibm** [vilmibm/tildemush#88]
i accidentally implemented a /move command when doing rooms/exits.

i don't think players should just have an arbitrary "teleport anywhere" command and i like that "move" can be treated as a regular action (just one that is scripted instead of sent by the user) so I'm thinking about adding a RESERVED_COMMANDS list that will block `/move` in the server's `core.py`.

is there a better way to do this?

**Comment by modgethanc** [comment]
hm, i do think it might be useful to have some commands that exist in general but aren't 100% accessible by a user normally; i can't think of a way to do this more gracefully than to just block normal usage of RESERVED_COMMANDS. so, even if only `/move` is in that list for now, i think it makes sense to have that.

**Comment by vilmibm** [comment]
After refactoring some stuff, the `/move` command no longer exists, so this issue is :heavy_check_mark:
