### ISSUE TITLE
support rlwrap style key combos and command history in main game prompt

### ISSUE THREAD

**Issue by vilmibm** [vilmibm/tildemush#89]
- [x] input history
- [ ] ctrl+{a,e,u,k}

**Comment by selfsame** [comment]
perhaps we follow weechat, where arrow keys up/down scroll through history and page up/down scroll the main game view

**Comment by modgethanc** [comment]
@selfsame yeah, i think that's a good idea/what my muscle memory keeps going for anyway.

**Comment by modgethanc** [comment]
should this ticket include things like catching ctrl-c, tab-completion, etc.?

i did a little hunting around and couldn't find an obvious urwid drop-in for rlwrap, so i'm starting to implement them manually.
